export const mainResource: {[key: string]: string} = {
    'anchor_big_popups@': 'anchor_big_popups.json',
    'big_popups@': 'big_popups.json',
    'btn14@': 'btn14.json',
    'btn13@': 'btn13.json',
    'btn2_ok@': 'btn2_ok.json',
    'anchor_btnUP_popup@': 'anchor_btnUP_popup.json',
    'pop_up@': 'pop_up.json',
    'btnPU3_popup@': 'btnPU3_popup.json',
    'btnPU3_win_lose@': 'btnPU3_win_lose.json',
    'popup_win_lose@': 'popup_win_lose.json',
    'anchor_btnUP_win_lose@': 'anchor_btnUP_win_lose.json',
    'btn_kof@': 'btn_kof.json',
    // 'popup@': 'popup.json',
    // 'rates@': 'rates.json',
    'rates@': 'rates.json',
    'btn1@': 'btn1.json',
    'btn4@': 'btn4.json',
    'btn5@': 'btn5.json',
    'btn6@': 'btn6.json',
    'btn11@': 'btn11.json',
    'btn10@': 'btn10.json',
    'btn9@': 'btn9.json',
    'btn15_arrow@': 'btn15_arrow.json',
    'btn7@': 'btn7.json',
    // 'mask_play@': 'mask_play.json',
    'slot_roll1@': 'slot_roll1.json',
    'slot_roll2@': 'slot_roll2.json',
    'slot_roll3@': 'slot_roll3.json',
    'lever@': 'lever.json',
    'anchor_game_buttons@': 'anchor_game_buttons.json',

    'onboarding@': 'onboarding.json',
    // 'btn_skip@': 'btn_skip.json',
    // eslint-disable-next-line no-undef
    keyboardBack: __DEV__ ? 'keyboardBack.png' : '/assets/keyboardBack.webp'
};
