export const mainResource: { [key: string]: string } = {
    'black_square@': 'black_square.json',
    'bonus_flag@': 'bonus_flag.json',
    'bonus@': 'bonus.json',
    'btn_anchor@': 'btn_anchor.json',
    'btn_back@': 'btn_back.json',
    'btn_bet@': 'btn_bet.json',
    'btn_bg@': 'btn_bg.json',
    'btn_currency@': 'btn_currency.json',
    'btn_more@': 'btn_more.json',
    'btn_result@': 'btn_result.json',
    'btn_skull@': 'btn_skull.json',
    'btn10@': 'btn10.json',
    'btn13@': 'btn13.json',
    'btn14@': 'btn14.json',
    'btn5@': 'btn5.json',
    'btn7@': 'btn7.json',
    'btn8@': 'btn8.json',
    'btn9@': 'btn9.json',
    'coin_bet1@': 'coin_bet1.json',
    'coin_bet2@': 'coin_bet2.json',
    'coin_bet3@': 'coin_bet3.json',
    'coin_bet4@': 'coin_bet4.json',
    'coin_bet5@': 'coin_bet5.json',
    'coin_bet6@': 'coin_bet6.json',
    'mask_play@': 'mask_play.json',
    'dynamic_onboarding@': 'dynamic_onboarding.json',
    'parrots@': 'parrots.json',
    'popup_bg@': 'popup_bg.json',
    'ppp_btn_anchor@': 'ppp_btn_anchor.json',
    'ppp_btnPU4@': 'ppp_btnPU4.json',
    'ppp_btnPU5@': 'ppp_btnPU5.json',
    'ppp_pop_up@': 'ppp_pop_up.json',
    'big_popups_anchor@': 'big_popups_anchor.json',
    'btn_bonus_play@': 'btn_bonus_play.json',
    'rope@': 'rope.json',
    'rope_top@': 'rope_top.json',
    'wallet_h@': 'wallet_h.json',
    'dice_l@': 'dice_l.json',
    'dice_r@': 'dice_r.json',
    'version@': 'version.json',
    'dice_result@': 'dice_result.json',
    'sign@': 'sign.json',
    'dynamic_light@': 'dynamic_light.json',
    'dice_anchor_top@': 'dice_anchor_top.json',
    'dynamic_button-skip_top-right@': 'dynamic_button-skip_top-right.json',
    // eslint-disable-next-line no-undef
    keyboardBack: __DEV__ ? 'keyboardBack.png' : '/assets/keyboardBack.webp'
};

/* const a = [
    'background.json',
    'black_square.json',
    'bonus_flag.json',
    'bonus.json',
    'btn_anchor.json',
    'btn_back.json',
    'btn_bet.json',
    'btn_bg.json',
    'btn_currency.json',
    'btn_more.json',
    'btn_result.json',
    'btn_skull.json',
    'btn10.json',
    'btn13.json',
    'btn14.json',
    'btn15.json',
    'btn5.json',
    'btn7.json',
    'btn8.json',
    'btn9.json',
    'coin_bet.json',
    'coin_bet1.json',
    'coin_bet2.json',
    'coin_bet3.json',
    'coin_bet4.json',
    'coin_bet5.json',
    'coin_bet6.json',
    'dice_l.json',
    'dice_r.json',
    'foreground.json',
    'girl.json',
    'loading.json',
    'logo.json',
    'mask_play.json',
    'onboarding.json',
    'parrots.json',
    'popup_bg.json',
    'ppp_btn_anchor.json',
    'ppp_btnPU4.json',
    'ppp_btnPU5.json',
    'ppp_currency_anchor.json',
    'ppp_pop_up.json',
    'rope.json'
];

const a1 = {};
a.forEach(item => {
    a1[item.replace('.json', '@')] = item;
});

JSON.stringify(a1); */
